services:
  fleet-telemetry-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./examples/config.json:/etc/fleet-telemetry-consumer/config.json:ro
    command: ["/fleet-telemetry-consumer", "-config", "/etc/fleet-telemetry-consumer/config.json"]
    ports:
      - "2112:2112"  # Expose Prometheus metrics port