version: '3.8'

services:
  tesla-http-proxy:
    image: tesla/vehicle-command:latest
    ports:
      - "4443:4443"
    environment:
      - TESLA_HTTP_PROXY_TLS_CERT=/secrets/tesla-ssl/tls.crt
      - TESLA_HTTP_PROXY_TLS_KEY=/secrets/tesla-ssl/tls.key
      - TESLA_HTTP_PROXY_HOST=0.0.0.0
      - TESLA_HTTP_PROXY_PORT=4443
      - TESLA_HTTP_PROXY_TIMEOUT=10s
      - TESLA_KEY_FILE=/secret/private-key.pem
      - TESLA_VERBOSE=true
    volumes:
      - ./secrets/tesla-ssl/tls.crt:/secrets/tesla-ssl/tls.crt:ro
      - ./secrets/tesla-ssl/tls.key:/secrets/tesla-ssl/tls.key:ro
      - ./secrets/fleet-api/private-key.pem:/secret/private-key.pem:ro
  # fleet-telemetry-consumer:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - tesla-http-proxy
  #   volumes:
  #     - ./secrets/fleet-telemetry-ssl/:/app/secrets/fleet-telemetry-ssl:ro
  #     - ./secrets/pg/:/app/secrets/pg:ro
  #     - ./secrets/fleet-api/:/app/secrets/fleet-api:ro
  #     - ./secrets/tesla-ssl/:/app/secrets/tesla-ssl:ro
