apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: fleet-telemetry-consumer-config
    files:
      - config.json
    options:
      disableNameSuffixHash: true 