{
 "title": "Vehicle Data",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Vehicle Locations",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"Latitude\"}) by (vin)",
     "legendFormat": "{{vin}} Latitude"
    },
    {
     "expr": "avg(vehicle_data{field=\"Longitude\"}) by (vin)",
     "legendFormat": "{{vin}} Longitude"
    }
   ]
  },
  {
   "title": "List of VIN's",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "group by (vin) (vehicle_data)", "legendFormat": "{{vin}}" }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"BatteryLevel\"}) by (vin)",
     "legendFormat": "{{vin}} Battery Level"
    }
   ]
  },
  {
   "title": "Temperature Readings (Inside & Outside)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"InsideTemp\"}) by (vin)",
     "legendFormat": "{{vin}} Inside Temp"
    },
    {
     "expr": "avg(vehicle_data{field=\"OutsideTemp\"}) by (vin)",
     "legendFormat": "{{vin}} Outside Temp"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"Odometer\"}) by (vin)",
     "legendFormat": "{{vin}} Odometer"
    }
   ]
  },
  {
   "title": "VehicleSpeed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"VehicleSpeed\"}) by (vin)",
     "legendFormat": "{{vin}} VehicleSpeed"
    }
   ]
  },
  {
   "title": "TimeToFullCharge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"TimeToFullCharge\"}) by (vin)",
     "legendFormat": "{{vin}} TimeToFullCharge"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"Gear\"}) by (vin)",
     "legendFormat": "{{vin}} Gear"
    }
   ]
  }
 ]
}