apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tesla
resources:
  - fleet-telemetry.yaml
  - certificate.yaml
  - tlsroute.yaml
  - secrets.yaml
  - public-key-webserver.yaml
  - pg.yaml
  - fleet-telemetry-consumer.yaml
configMapGenerator:
  - name: fleet-telemetry-config
    files:
      - config.json