name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fleet-telemetry-consumer:latest



name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"  # Triggers on all branches
    tags:
      - "v*.*.*"  # Triggers on tag push for versioned tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login quay.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get tag or commit SHA
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ -n "${{ github.ref_name }}" ]; then
            echo "image_tag=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "image_tag=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: make build

      - name: Tag Docker Image
        run: docker tag fleet-telemetry-consumer quay.io/rajsinghcpre/fleet-telemetry-consumer:${{ env.image_tag }}

      - name: Push Docker Image
        run: docker push quay.io/rajsinghcpre/fleet-telemetry-consumer:${{ env.image_tag }}